title:              Yet Another Name Generator
email:              zachsand@utexas.edu
description:        Simple name generator
author:             Zachary Sanders
baseurl:            "/yet-another-name-generator"
url:                "https://ZachSand.github.io"

remote_theme: ErwanJes/jekyll-theme-onepage

# Social Profiles
github_username:    ZachSand

# Build settings
markdown:           kramdown